<?php
/**
 *magento2 Magento_Theme html copyright template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>
<div class="copyright-wrap item">
    <small class="copyright">
        <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
    </small>
</div>
<script type="text/x-magento-init">
    {
        ".footer-action-toggle": {
            "Magento_Theme/js/footer-toggle": {}
        }
    }
</script>
