<?php
/**
 *magento2 Magento_Theme html copyright template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>
<div class="copyright-wrap item">
    <small class="copyright">
        <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
    </small>
</div>
<script type="text/x-magento-init">
    {
        ".footer-navigation": {
            "accordion": {
                "active": "0 1 2 3 4 5",
                "collapsible": true,
                "openedState": "active",
                "multipleCollapsible": true
            }
        }
    }
</script>
