<?php
/**
 *magento2 Magento_Theme html custom_menu-links template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>
<ul class="additional-links">
    <li class="signification">
        <a class="signification link"><?= $block->escapeHtml(__('Sign In')) ?></a>
    </li>
    <li class="store-locator">
        <a class="store-locator link"><?= $block->escapeHtml(__('Store Locator')) ?></a>
    </li>
    <li class="contact-us">
        <a class="contact-us link"><?= $block->escapeHtml(__('Contact Us')) ?></a>
    </li>
    <li class="orders-status">
        <a class="orders-status link"><?= $block->escapeHtml(__('Order Status')) ?></a>
    </li>
    <li class="email-notification">
        <a class="email-notification link"><?= $block->escapeHtml(__('Sign Up For Emails')) ?></a>
    </li>
    <li class="request-catalog">
        <a class="request-catalog link"><?= $block->escapeHtml(__('Request A Catalog')) ?></a>
    </li>
</ul>
