<?php
/**
 *StyleGuide_AuthPopUp account template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */

/** @var \Magento\Customer\Block\Account\AuthenticationPopup $block */
?>

<div id="ajaxlogin-popup" data-bind="scope:'ajaxLogin'" style="display: none;">
    <script>
        window.ajaxLogin = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#ajaxlogin-popup": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>
