<?php
/**
 *Magento_Customer account custom-authentication-popup template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>
<div class="account-icon auth-btn">
    <span class="signification-btn" data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "baseToggleClass": "expanded", "toggleContainers": ".signification-modal"}}'
    ><?= $block->escapeHtml(__('Sign In')) ?></span>
</div>
<script>
    require([
        'jquery',
        'toggleAdvanced'
    ], function ($) {
        'use strict';

        $(".signification-btn").toggleAdvanced();
    });
</script>
