<p><?= $block->escapeHtml(__('Got questions? Need advice? Our customer service team is just a click or call away.')) ?></p>
<ul>
    <li>
        <a href="tel:8445325625"><?= $block->escapeHtml(__('844-532-JMCL (5625)')) ?></a>
        <span><?= $block->escapeHtml(__('Monday-Friday, 9:30am - 5:30pm EST')) ?></span>
    </li>
    <li>
        <a href="#"><?= $block->escapeHtml(__('Contact a Personal Stylist')) ?></a>
    </li>
    <li>
        <a href="#"><?= $block->escapeHtml(__('customerservice@jmclaughlin.com')) ?></a>
    </li>
    <li>
        <a href="#"><?= $block->escapeHtml(__('Live Chat')) ?></a>
    </li>
</ul>







