<?php
/**
 *magento2 module Styleguide template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>
<div class="styleguide-main-banner">
    <img class="sg-top-banner-img" src="<?php echo $this->getViewFileUrl('StyleGuide_NewPage::images/styleguide.png'); ?>" alt="styleguide.png">
</div>
<div class="styleguide-colors">
    <h2 class="styleguide-heading"><?= __('colors') ?></h2>
    <div class="color-blocks">
        <div class="color-block-wrapper sg-c-blue-navy">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('blue navy') ?></dt>
                    <dd>rgb: 10 / 33 / 72</dd>
                    <dd>hex: #0a2148</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-blue-dark">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('blue dark') ?></dt>
                    <dd>rgb: 20 / 68 / 110</dd>
                    <dd>hex: #14446e</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-blue">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('blue') ?></dt>
                    <dd>rgb: 48 / 93 / 148</dd>
                    <dd>hex: #305d94 </dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-blue-light">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('blue light') ?></dt>
                    <dd>rgb: 84 / 188 / 235</dd>
                    <dd>hex: #54bceb</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-orange">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('orange') ?></dt>
                    <dd>rgb: 239 / 144 / 34</dd>
                    <dd>hex: #ef9022</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-almost-black">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('almost black') ?></dt>
                    <dd>rgb: 34 / 34 / 34</dd>
                    <dd>hex: #222222</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-gray-dark">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('gray dark') ?></dt>
                    <dd>rgb: 68 / 68 / 68</dd>
                    <dd>hex: #444444</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-gray">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('gray') ?></dt>
                    <dd>rgb: 136 / 136 / 136</dd>
                    <dd>hex: #888888</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-gray-light">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('gray light') ?></dt>
                    <dd>rgb: 204 / 204 / 204</dd>
                    <dd>hex: #cccccc</dd>
                </dl>
            </div>
        </div>
        <div class="color-block-wrapper sg-c-whitesmoke">
            <div class="color-block"></div>
            <div class="color-txt-info">
                <dl>
                    <dt><?= __('white smoke') ?></dt>
                    <dd>rgb: 238 / 238 / 238</dd>
                    <dd>hex: #eeeeee</dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<div class="styleguide-typography">
    <h2 class="styleguide-heading"><?= __('typography') ?></h2>
    <div class="fonts">
        <h4 class="typo-heading"><?= __('font families') ?></h4>
        <dl>
            <dt>Roboto - Regular</dt>
            <dd class="sg-font-Roboto-regular">
                <span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span>
                <span>abcdefghijklmnopqrstuvwxyz0123456789</span>
            </dd>
            <dt>Roboto - Medium</dt>
            <dd class="sg-font-Roboto-medium">
                <span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span>
                <span>abcdefghijklmnopqrstuvwxyz0123456789</span>
            </dd>
            <dt>Roboto - Bold</dt>
            <dd class="sg-font-Roboto-bold">
                <span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span>
                <span>abcdefghijklmnopqrstuvwxyz0123456789</span>
            </dd>
            <dt>Roboto - Regular Italic</dt>
            <dd class="sg-font-Roboto-regular-italic">
                <span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span>
                <span>abcdefghijklmnopqrstuvwxyz0123456789</span>
            </dd>
            <dt>Roboto - Medium Italic</dt>
            <dd class="sg-font-Roboto-medium-italic">
                <span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span>
                <span>abcdefghijklmnopqrstuvwxyz0123456789</span>
            </dd>
        </dl>
        <h4 class="typo-heading"><?= __('headings') ?></h4>
        <dl>
            <dt>Roboto Condanced - Regular
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h1 class="heading-regular-c"><?= __('We are where you live, work & play') ?></h1></dd>
            <dt>Roboto Condanced - Regular
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h2 class="heading-regular-c"><?= __('We are where you live, work & play') ?></h2></dd>
            <dt>Roboto Condanced - Regular
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h3 class="heading-regular-c"><?= __('We are where you live, work & play') ?></h3></dd>
            <dt>Roboto Condanced - Regular
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h4 class="heading-regular-c"><?= __('We are where you live, work & play') ?></h4></dd>
            <dt>Roboto Condanced - Regular
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h5 class="heading-regular-c"><?= __('We are where you live, work & play') ?></h5></dd>
            <dt>Roboto Condanced - Regular
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h6 class="heading-regular-c"><?= __('We are where you live, work & play') ?></h6></dd>
        </dl>
        <h4 class="typo-heading"><?= __('headings italic') ?></h4>
        <dl>
            <dt>Roboto Condanced - Italic
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h1 class="heading-regular-ci"><?= __('We are where you live, work & play') ?></h1></dd>
            <dt>Roboto Condanced - Italic
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h2 class="heading-regular-ci"><?= __('We are where you live, work & play') ?></h2></dd>
            <dt>Roboto Condanced - Italic
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h3 class="heading-regular-ci"><?= __('We are where you live, work & play') ?></h3></dd>
            <dt>Roboto Condanced - Italic
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h4 class="heading-regular-ci"><?= __('We are where you live, work & play') ?></h4></dd>
            <dt>Roboto Condanced - Italic
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h5 class="heading-regular-ci"><?= __('We are where you live, work & play') ?></h5></dd>
            <dt>Roboto Condanced - Italic
                <span>56 / 64 / 2</span>
            </dt>
            <dd><h6 class="heading-regular-ci"><?= __('We are where you live, work & play') ?></h6></dd>
        </dl>
    </div>
</div>
<div class="styleguide-forms">
    <h2 class="styleguide-heading"><?= __('forms') ?></h2>
    <form action="#" class="styleguide-form">
        <p class="required title"><?= __('* required fields') ?></p>
        <fieldset class="sg-fieldset">
            <div class="field">
                <label class="sg-label" for="sg-text"><?= __('text input') ?></label>
                <div class="sg-input-wrap">
                    <input type="text" id="sg-input-txt" class="input-txt" name="sg-text" value="" title="text input" autocomplete="off" tabindex="1">
                </div>
            </div>
            <div class="field">
                <label class="sg-label" for="sg-seacrh"><?= __('search') ?></label>
                <div class="sg-input-wrap">
                    <input type="text" id="sg-input-seacrh" class="input-txt" name="sg-seacrh" value="what are you looking for?" title="search input" autocomplete="off" tabindex="2">
                </div>
            </div>
            <div class="field required">
                <label class="sg-label" for="sg-url"><?= __('url input') ?></label>
                <div class="sg-input-wrap">
                    <input type="text" id="sg-inpt-url" class="input-txt" name="sg-url" value="" title="url input" autocomplete="off" placeholder="http://qwerty.com" required="true" tabindex="3">
                </div>
            </div>
            <div class="field required">
                <label class="sg-label" for="sg-tel"><?= __('telephone input') ?></label>
                <div class="sg-input-wrap">
                    <input type="tel" id="sg-input-tel" class="input-txt" name="sg-tel" value="123-123-123" title="telephone input" autocomplete="off" tabindex="4">
                </div>
            </div>
            <div class="field required">
                <label class="sg-label" for="sg-email-error"><?= __('email input - validation error') ?></label>
                <div class="sg-input-wrap">
                    <input type="email" class="input-txt" name="sg-email-error" value="asd#asd.com" autocomplete="off" tabindex="5">
                    <div class="validation-failed">
                        <?= __('Please enter a valid email, i.e johndoe@domain.com') ?> </div>
                </div>
            </div>
            <div class="field">
                <label class="sg-label" for="comment"><?= __('comment') ?></label>
                <div class="sg-input-wrap">
                    <input type="text" id="sg-comment" class="input-txt" name="comment" title="enter your comments" cols="5" rows="5" tabindex="6">
                </div>
            </div>
        </fieldset>
        <fieldset class="sg-fieldset">
            <div class="field">
                <label class="sg-label" for="sg-placeholder"><?= __('placeholder') ?></label>
                <div class="sg-input-wrap">
                    <input type="text" id="sg-placeholder" class="input-txt" name="sg-placeholder" value="" title="placeholder" placeholder="Search" autocomplete="off" tabindex="7">
                </div>
            </div>
            <div class="field required">
                <label class="sg-label" for="sg-email"><?= __('email input') ?></label>
                <div class="sg-input-wrap">
                    <input type="email" id="sg-email" class="input-txt" name="sg-email" placeholder="asd@asdas.com" autocomplete="off" tabindex="8" required="true">
                </div>
            </div>
            <div class="field required">
                <label class="sg-label" for="sg-password"><?= __('password input') ?></label>
                <div class="sg-input-wrap">
                    <input type="password" id="sg-password" class="input-txt" name="sg-password" value="password" autocomplete="off" tabindex="9" required="true">
                </div>
            </div>
            <div class="field">
                <label class="sg-label" for="sg-txt-focus"><?= __('text input - focus') ?></label>
                <div class="sg-input-wrap">
                    <input type="text" id="sg-txt-focus" class="input-txt" name="sg-txt-focus" value="" title="text input" autocomplete="off" tabindex="10">
                </div>
            </div>
            <div class="field required">
                <label class="sg-label" for="sg-email-valid"><?= __('email input - validation passed') ?></label>
                <div class="sg-input-wrap valid">
                    <input type="email" id="sg-email-valid" class="input-txt" name="sg-email-valid" value="asd@asd.com" autocomplete="off" tabindex="11">
                </div>
            </div>
            <div class="field sg-block-search">
                <label class="sg-label" for="sg-embed"><?= __('embed button') ?></label>
                <div class="sg-input-wrap">
                    <input type="text" id="sg-embed" class="input-txt embed-search" name="sg-embed" value="Gamecocks" placeholder="What are you looking for?" autocomplete="off" tabindex="12">
                </div>
                <div class="actions">
                    <button class="action seacrh embed" type="submit" tabindex="13"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </fieldset>
        <fieldset class="sg-fieldset sg-checkboxes">
            <div class="field cbox">
                <input type="checkbox" id="custom-cbox1" class="sg-checkbox" name="custom-cbox" tabindex="14">
                <label for="custom-cbox1" class="sg-label cbox">
                    <span><?= __('custom checkbox') ?></span>
                    <span class="checkmark">&nbsp;</span>
                </label>
            </div>
            <div class="field cbox">
                <input type="checkbox" id="custom-cbox2" class="sg-checkbox" name="custom-cbox" checked="checked" tabindex="15">
                <label for="custom-cbox2" class="sg-label cbox">
                    <span><?= __('custom checkbox active') ?></span>
                    <span class="checkmark">&nbsp;</span>
                </label>
            </div>
            <div class="field cbox">
                <input type="checkbox" id="custom-cbox3" class="sg-checkbox" name="custom-cbox" disabled="disabled" tabindex="16">
                <label for="custom-cbox3" class="sg-label cbox disabled">
                    <span><?= __('custom checkbox disabled') ?></span>
                    <span class="checkmark">&nbsp;</span>
                </label>
            </div>
        </fieldset>
        <fieldset class="sg-fieldset sg-checkboxes">
            <div class="field cbox">
                <input type="radio" id="custom-radio1" class="sg-radio" name="custom-radio" tabindex="17">
                <label for="custom-radio1" class="sg-label radio">
                    <span><?= __('custom radio') ?></span>
                    <span class="checkmark">&nbsp;</span>
                </label>
            </div>
            <div class="field cbox">
                <input type="radio" id="custom-radio2" class="sg-radio" checked="checked" name="custom-radio" tabindex="18">
                <label for="custom-radio2" class="sg-label radio">
                    <span><?= __('custom radio active') ?></span>
                    <span class="checkmark">&nbsp;</span>
                </label>
            </div>
            <div class="field cbox">
                <input type="radio" id="custom-radio3" class="sg-radio" disabled="disabled" name="custom-radio" tabindex="19">
                <label for="custom-radio" class="sg-label radio disabled">
                    <span><?= __('custom radio disabled') ?></span>
                    <span class="checkmark">&nbsp;</span>
                </label>
            </div>
        </fieldset>
        <fieldset class="sg-fieldset">
            <div class="field required">
                <label for="sg-select1" class="sg-label required"><?= __('state') ?></label>
                <div class="sg-input-wrap valid sg-section">
                    <select name="sg-select1" id="sg-select1" class="sg-select valid" title="custom select" tabindex="21">
                        <option value=""><?= __('Please select') ?></option>
                        <option value="1"><?= __('one') ?></option>
                        <option value="2"><?= __('two') ?></option>
                        <option value="3"><?= __('three') ?></option>
                        <option value="4"><?= __('four') ?></option>
                    </select>
                </div>
            </div>
            <div class="field required">
                <label for="sg-select2" class="sg-label required"><?= __('state') ?></label>
                <div class="sg-input-wrap">
                    <select name="sg-select2" id="sg-select2" class="sg-select disabled" title="custom select" disabled="" tabindex="22">
                        <option value=""><?= __('Please select') ?></option>
                        <option value="1"><?= __('one') ?></option>
                        <option value="2"><?= __('two') ?></option>
                        <option value="3"><?= __('three') ?></option>
                        <option value="4"><?= __('four') ?></option>
                    </select>
                </div>
            </div>
        </fieldset>
        <fieldset class="sg-fieldset">
            <div class="field required">
                <label for="sg-select3" class="sg-label required"><?= __('state') ?></label>
                <div class="sg-input-wrap">
                    <select name="sg-select3" id="sg-select3" class="sg-select valid" title="custom select" tabindex="23">
                        <option value=""><?= __('Please select') ?></option>
                        <option value="1"><?= __('one') ?></option>
                        <option value="2" selected><?= __('two') ?></option>
                        <option value="3"><?= __('three') ?></option>
                        <option value="4"><?= __('four') ?></option>
                    </select>
                </div>
            </div>
            <div class="field">
                <label for="sg-select4" class="sg-label required" tabindex="20"><?= __('state') ?></label>
                <div class="sg-input-wrap">
                    <select name="sg-select4" id="sg-select4" class="sg-select valid" title="custom select" tabindex="24">
                        <option value=""><?= __('Would you like to know more?') ?></option>
                        <option value="1"><?= __('yes') ?></option>
                        <option value="2"><?= __('no') ?></option>
                    </select>
                </div>
                <div class="validation-failed sg-section">
                    <?= __('Required. Please make a selection from the list.') ?>
                </div>
            </div>
        </fieldset>
    </form>
</div>
<div class="styleguide-buttons">
    <h2 class="styleguide-heading"><?= __('buttons') ?></h2>
    <div class="sg-actions-toolbar">
        <div class="actions">
            <a class="action primary sg" tabindex="24"><span class=""><?= __('primary') ?></span></a>
            <button class="action button sg" tabindex="25"><span><?= __('call to action') ?></span></button>
            <button class="action button sg secondary" tabindex="26"><span><?= __('secondary') ?></span></button>
        </div>
    </div>
</div>
